// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.22.2
// source: proto/sessionhub.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SessionHubService_ValidateApiKey_FullMethodName         = "/sessionhub.SessionHubService/ValidateApiKey"
	SessionHubService_GetProjects_FullMethodName            = "/sessionhub.SessionHubService/GetProjects"
	SessionHubService_CreateProject_FullMethodName          = "/sessionhub.SessionHubService/CreateProject"
	SessionHubService_CreateSession_FullMethodName          = "/sessionhub.SessionHubService/CreateSession"
	SessionHubService_UpsertSession_FullMethodName          = "/sessionhub.SessionHubService/UpsertSession"
	SessionHubService_GetSession_FullMethodName             = "/sessionhub.SessionHubService/GetSession"
	SessionHubService_UpdateSession_FullMethodName          = "/sessionhub.SessionHubService/UpdateSession"
	SessionHubService_StreamInteractions_FullMethodName     = "/sessionhub.SessionHubService/StreamInteractions"
	SessionHubService_AddInteractionsBatch_FullMethodName   = "/sessionhub.SessionHubService/AddInteractionsBatch"
	SessionHubService_GetProjectObservations_FullMethodName = "/sessionhub.SessionHubService/GetProjectObservations"
	SessionHubService_GetUserPreferences_FullMethodName     = "/sessionhub.SessionHubService/GetUserPreferences"
	SessionHubService_UploadAttachment_FullMethodName       = "/sessionhub.SessionHubService/UploadAttachment"
	SessionHubService_UploadPlanFile_FullMethodName         = "/sessionhub.SessionHubService/UploadPlanFile"
	SessionHubService_GetSessionQuota_FullMethodName        = "/sessionhub.SessionHubService/GetSessionQuota"
	SessionHubService_CreateTeam_FullMethodName             = "/sessionhub.SessionHubService/CreateTeam"
	SessionHubService_GetTeam_FullMethodName                = "/sessionhub.SessionHubService/GetTeam"
	SessionHubService_UpdateTeam_FullMethodName             = "/sessionhub.SessionHubService/UpdateTeam"
	SessionHubService_DeleteTeam_FullMethodName             = "/sessionhub.SessionHubService/DeleteTeam"
	SessionHubService_ListUserTeams_FullMethodName          = "/sessionhub.SessionHubService/ListUserTeams"
	SessionHubService_InviteMember_FullMethodName           = "/sessionhub.SessionHubService/InviteMember"
	SessionHubService_AcceptInvitation_FullMethodName       = "/sessionhub.SessionHubService/AcceptInvitation"
	SessionHubService_RevokeInvitation_FullMethodName       = "/sessionhub.SessionHubService/RevokeInvitation"
	SessionHubService_ListPendingInvitations_FullMethodName = "/sessionhub.SessionHubService/ListPendingInvitations"
	SessionHubService_RemoveMember_FullMethodName           = "/sessionhub.SessionHubService/RemoveMember"
	SessionHubService_UpdateMemberRole_FullMethodName       = "/sessionhub.SessionHubService/UpdateMemberRole"
	SessionHubService_ListMembers_FullMethodName            = "/sessionhub.SessionHubService/ListMembers"
	SessionHubService_TransferOwnership_FullMethodName      = "/sessionhub.SessionHubService/TransferOwnership"
	SessionHubService_GetTeamPublicKey_FullMethodName       = "/sessionhub.SessionHubService/GetTeamPublicKey"
	SessionHubService_GetUserPublicKey_FullMethodName       = "/sessionhub.SessionHubService/GetUserPublicKey"
	SessionHubService_GetTeamSkills_FullMethodName          = "/sessionhub.SessionHubService/GetTeamSkills"
	SessionHubService_CreateTeamSkill_FullMethodName        = "/sessionhub.SessionHubService/CreateTeamSkill"
)

// SessionHubServiceClient is the client API for SessionHubService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Main service for SessionHub backend
type SessionHubServiceClient interface {
	// Authentication
	ValidateApiKey(ctx context.Context, in *ValidateApiKeyRequest, opts ...grpc.CallOption) (*ValidateApiKeyResponse, error)
	// Projects
	GetProjects(ctx context.Context, in *GetProjectsRequest, opts ...grpc.CallOption) (*GetProjectsResponse, error)
	CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*Project, error)
	// Sessions
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error)
	UpsertSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*UpsertSessionResponse, error)
	GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*Session, error)
	UpdateSession(ctx context.Context, in *UpdateSessionRequest, opts ...grpc.CallOption) (*Session, error)
	// Interactions - Streaming for large imports
	StreamInteractions(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StreamInteractionsRequest, StreamInteractionsResponse], error)
	// Batch operations (alternative to streaming)
	AddInteractionsBatch(ctx context.Context, in *AddInteractionsBatchRequest, opts ...grpc.CallOption) (*AddInteractionsBatchResponse, error)
	// Observations for context injection
	GetProjectObservations(ctx context.Context, in *GetProjectObservationsRequest, opts ...grpc.CallOption) (*GetProjectObservationsResponse, error)
	// User preferences
	GetUserPreferences(ctx context.Context, in *GetUserPreferencesRequest, opts ...grpc.CallOption) (*GetUserPreferencesResponse, error)
	// Attachment storage
	UploadAttachment(ctx context.Context, in *UploadAttachmentRequest, opts ...grpc.CallOption) (*UploadAttachmentResponse, error)
	// Plan file storage (uploads plan .md files to team-based storage)
	UploadPlanFile(ctx context.Context, in *UploadPlanFileRequest, opts ...grpc.CallOption) (*UploadPlanFileResponse, error)
	// Session quota for free tier limit enforcement
	GetSessionQuota(ctx context.Context, in *GetSessionQuotaRequest, opts ...grpc.CallOption) (*GetSessionQuotaResponse, error)
	// Team CRUD
	CreateTeam(ctx context.Context, in *CreateTeamRequest, opts ...grpc.CallOption) (*Team, error)
	GetTeam(ctx context.Context, in *GetTeamRequest, opts ...grpc.CallOption) (*Team, error)
	UpdateTeam(ctx context.Context, in *UpdateTeamRequest, opts ...grpc.CallOption) (*Team, error)
	DeleteTeam(ctx context.Context, in *DeleteTeamRequest, opts ...grpc.CallOption) (*DeleteTeamResponse, error)
	ListUserTeams(ctx context.Context, in *ListUserTeamsRequest, opts ...grpc.CallOption) (*ListUserTeamsResponse, error)
	// Team Membership
	InviteMember(ctx context.Context, in *InviteMemberRequest, opts ...grpc.CallOption) (*InviteMemberResponse, error)
	AcceptInvitation(ctx context.Context, in *AcceptInvitationRequest, opts ...grpc.CallOption) (*AcceptInvitationResponse, error)
	RevokeInvitation(ctx context.Context, in *RevokeInvitationRequest, opts ...grpc.CallOption) (*RevokeInvitationResponse, error)
	ListPendingInvitations(ctx context.Context, in *ListPendingInvitationsRequest, opts ...grpc.CallOption) (*ListPendingInvitationsResponse, error)
	RemoveMember(ctx context.Context, in *RemoveMemberRequest, opts ...grpc.CallOption) (*RemoveMemberResponse, error)
	UpdateMemberRole(ctx context.Context, in *UpdateMemberRoleRequest, opts ...grpc.CallOption) (*UpdateMemberRoleResponse, error)
	ListMembers(ctx context.Context, in *ListMembersRequest, opts ...grpc.CallOption) (*ListMembersResponse, error)
	TransferOwnership(ctx context.Context, in *TransferOwnershipRequest, opts ...grpc.CallOption) (*TransferOwnershipResponse, error)
	// Team Encryption Keys
	GetTeamPublicKey(ctx context.Context, in *GetTeamPublicKeyRequest, opts ...grpc.CallOption) (*GetTeamPublicKeyResponse, error)
	// User Encryption Keys (for personal sessions)
	GetUserPublicKey(ctx context.Context, in *GetUserPublicKeyRequest, opts ...grpc.CallOption) (*GetUserPublicKeyResponse, error)
	// Get approved team skills for syncing to plugin as SKILL.md files
	GetTeamSkills(ctx context.Context, in *GetTeamSkillsRequest, opts ...grpc.CallOption) (*GetTeamSkillsResponse, error)
	// Create a team skill draft from the plugin (local → team push)
	CreateTeamSkill(ctx context.Context, in *CreateTeamSkillRequest, opts ...grpc.CallOption) (*CreateTeamSkillResponse, error)
}

type sessionHubServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSessionHubServiceClient(cc grpc.ClientConnInterface) SessionHubServiceClient {
	return &sessionHubServiceClient{cc}
}

func (c *sessionHubServiceClient) ValidateApiKey(ctx context.Context, in *ValidateApiKeyRequest, opts ...grpc.CallOption) (*ValidateApiKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateApiKeyResponse)
	err := c.cc.Invoke(ctx, SessionHubService_ValidateApiKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionHubServiceClient) GetProjects(ctx context.Context, in *GetProjectsRequest, opts ...grpc.CallOption) (*GetProjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProjectsResponse)
	err := c.cc.Invoke(ctx, SessionHubService_GetProjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionHubServiceClient) CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*Project, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Project)
	err := c.cc.Invoke(ctx, SessionHubService_CreateProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionHubServiceClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSessionResponse)
	err := c.cc.Invoke(ctx, SessionHubService_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionHubServiceClient) UpsertSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*UpsertSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertSessionResponse)
	err := c.cc.Invoke(ctx, SessionHubService_UpsertSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionHubServiceClient) GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, SessionHubService_GetSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionHubServiceClient) UpdateSession(ctx context.Context, in *UpdateSessionRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, SessionHubService_UpdateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionHubServiceClient) StreamInteractions(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StreamInteractionsRequest, StreamInteractionsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SessionHubService_ServiceDesc.Streams[0], SessionHubService_StreamInteractions_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamInteractionsRequest, StreamInteractionsResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SessionHubService_StreamInteractionsClient = grpc.ClientStreamingClient[StreamInteractionsRequest, StreamInteractionsResponse]

func (c *sessionHubServiceClient) AddInteractionsBatch(ctx context.Context, in *AddInteractionsBatchRequest, opts ...grpc.CallOption) (*AddInteractionsBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddInteractionsBatchResponse)
	err := c.cc.Invoke(ctx, SessionHubService_AddInteractionsBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionHubServiceClient) GetProjectObservations(ctx context.Context, in *GetProjectObservationsRequest, opts ...grpc.CallOption) (*GetProjectObservationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProjectObservationsResponse)
	err := c.cc.Invoke(ctx, SessionHubService_GetProjectObservations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionHubServiceClient) GetUserPreferences(ctx context.Context, in *GetUserPreferencesRequest, opts ...grpc.CallOption) (*GetUserPreferencesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserPreferencesResponse)
	err := c.cc.Invoke(ctx, SessionHubService_GetUserPreferences_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionHubServiceClient) UploadAttachment(ctx context.Context, in *UploadAttachmentRequest, opts ...grpc.CallOption) (*UploadAttachmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadAttachmentResponse)
	err := c.cc.Invoke(ctx, SessionHubService_UploadAttachment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionHubServiceClient) UploadPlanFile(ctx context.Context, in *UploadPlanFileRequest, opts ...grpc.CallOption) (*UploadPlanFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadPlanFileResponse)
	err := c.cc.Invoke(ctx, SessionHubService_UploadPlanFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionHubServiceClient) GetSessionQuota(ctx context.Context, in *GetSessionQuotaRequest, opts ...grpc.CallOption) (*GetSessionQuotaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionQuotaResponse)
	err := c.cc.Invoke(ctx, SessionHubService_GetSessionQuota_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionHubServiceClient) CreateTeam(ctx context.Context, in *CreateTeamRequest, opts ...grpc.CallOption) (*Team, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Team)
	err := c.cc.Invoke(ctx, SessionHubService_CreateTeam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionHubServiceClient) GetTeam(ctx context.Context, in *GetTeamRequest, opts ...grpc.CallOption) (*Team, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Team)
	err := c.cc.Invoke(ctx, SessionHubService_GetTeam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionHubServiceClient) UpdateTeam(ctx context.Context, in *UpdateTeamRequest, opts ...grpc.CallOption) (*Team, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Team)
	err := c.cc.Invoke(ctx, SessionHubService_UpdateTeam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionHubServiceClient) DeleteTeam(ctx context.Context, in *DeleteTeamRequest, opts ...grpc.CallOption) (*DeleteTeamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTeamResponse)
	err := c.cc.Invoke(ctx, SessionHubService_DeleteTeam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionHubServiceClient) ListUserTeams(ctx context.Context, in *ListUserTeamsRequest, opts ...grpc.CallOption) (*ListUserTeamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUserTeamsResponse)
	err := c.cc.Invoke(ctx, SessionHubService_ListUserTeams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionHubServiceClient) InviteMember(ctx context.Context, in *InviteMemberRequest, opts ...grpc.CallOption) (*InviteMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InviteMemberResponse)
	err := c.cc.Invoke(ctx, SessionHubService_InviteMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionHubServiceClient) AcceptInvitation(ctx context.Context, in *AcceptInvitationRequest, opts ...grpc.CallOption) (*AcceptInvitationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptInvitationResponse)
	err := c.cc.Invoke(ctx, SessionHubService_AcceptInvitation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionHubServiceClient) RevokeInvitation(ctx context.Context, in *RevokeInvitationRequest, opts ...grpc.CallOption) (*RevokeInvitationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeInvitationResponse)
	err := c.cc.Invoke(ctx, SessionHubService_RevokeInvitation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionHubServiceClient) ListPendingInvitations(ctx context.Context, in *ListPendingInvitationsRequest, opts ...grpc.CallOption) (*ListPendingInvitationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPendingInvitationsResponse)
	err := c.cc.Invoke(ctx, SessionHubService_ListPendingInvitations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionHubServiceClient) RemoveMember(ctx context.Context, in *RemoveMemberRequest, opts ...grpc.CallOption) (*RemoveMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveMemberResponse)
	err := c.cc.Invoke(ctx, SessionHubService_RemoveMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionHubServiceClient) UpdateMemberRole(ctx context.Context, in *UpdateMemberRoleRequest, opts ...grpc.CallOption) (*UpdateMemberRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateMemberRoleResponse)
	err := c.cc.Invoke(ctx, SessionHubService_UpdateMemberRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionHubServiceClient) ListMembers(ctx context.Context, in *ListMembersRequest, opts ...grpc.CallOption) (*ListMembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMembersResponse)
	err := c.cc.Invoke(ctx, SessionHubService_ListMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionHubServiceClient) TransferOwnership(ctx context.Context, in *TransferOwnershipRequest, opts ...grpc.CallOption) (*TransferOwnershipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferOwnershipResponse)
	err := c.cc.Invoke(ctx, SessionHubService_TransferOwnership_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionHubServiceClient) GetTeamPublicKey(ctx context.Context, in *GetTeamPublicKeyRequest, opts ...grpc.CallOption) (*GetTeamPublicKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTeamPublicKeyResponse)
	err := c.cc.Invoke(ctx, SessionHubService_GetTeamPublicKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionHubServiceClient) GetUserPublicKey(ctx context.Context, in *GetUserPublicKeyRequest, opts ...grpc.CallOption) (*GetUserPublicKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserPublicKeyResponse)
	err := c.cc.Invoke(ctx, SessionHubService_GetUserPublicKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionHubServiceClient) GetTeamSkills(ctx context.Context, in *GetTeamSkillsRequest, opts ...grpc.CallOption) (*GetTeamSkillsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTeamSkillsResponse)
	err := c.cc.Invoke(ctx, SessionHubService_GetTeamSkills_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionHubServiceClient) CreateTeamSkill(ctx context.Context, in *CreateTeamSkillRequest, opts ...grpc.CallOption) (*CreateTeamSkillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTeamSkillResponse)
	err := c.cc.Invoke(ctx, SessionHubService_CreateTeamSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SessionHubServiceServer is the server API for SessionHubService service.
// All implementations must embed UnimplementedSessionHubServiceServer
// for forward compatibility.
//
// Main service for SessionHub backend
type SessionHubServiceServer interface {
	// Authentication
	ValidateApiKey(context.Context, *ValidateApiKeyRequest) (*ValidateApiKeyResponse, error)
	// Projects
	GetProjects(context.Context, *GetProjectsRequest) (*GetProjectsResponse, error)
	CreateProject(context.Context, *CreateProjectRequest) (*Project, error)
	// Sessions
	CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error)
	UpsertSession(context.Context, *CreateSessionRequest) (*UpsertSessionResponse, error)
	GetSession(context.Context, *GetSessionRequest) (*Session, error)
	UpdateSession(context.Context, *UpdateSessionRequest) (*Session, error)
	// Interactions - Streaming for large imports
	StreamInteractions(grpc.ClientStreamingServer[StreamInteractionsRequest, StreamInteractionsResponse]) error
	// Batch operations (alternative to streaming)
	AddInteractionsBatch(context.Context, *AddInteractionsBatchRequest) (*AddInteractionsBatchResponse, error)
	// Observations for context injection
	GetProjectObservations(context.Context, *GetProjectObservationsRequest) (*GetProjectObservationsResponse, error)
	// User preferences
	GetUserPreferences(context.Context, *GetUserPreferencesRequest) (*GetUserPreferencesResponse, error)
	// Attachment storage
	UploadAttachment(context.Context, *UploadAttachmentRequest) (*UploadAttachmentResponse, error)
	// Plan file storage (uploads plan .md files to team-based storage)
	UploadPlanFile(context.Context, *UploadPlanFileRequest) (*UploadPlanFileResponse, error)
	// Session quota for free tier limit enforcement
	GetSessionQuota(context.Context, *GetSessionQuotaRequest) (*GetSessionQuotaResponse, error)
	// Team CRUD
	CreateTeam(context.Context, *CreateTeamRequest) (*Team, error)
	GetTeam(context.Context, *GetTeamRequest) (*Team, error)
	UpdateTeam(context.Context, *UpdateTeamRequest) (*Team, error)
	DeleteTeam(context.Context, *DeleteTeamRequest) (*DeleteTeamResponse, error)
	ListUserTeams(context.Context, *ListUserTeamsRequest) (*ListUserTeamsResponse, error)
	// Team Membership
	InviteMember(context.Context, *InviteMemberRequest) (*InviteMemberResponse, error)
	AcceptInvitation(context.Context, *AcceptInvitationRequest) (*AcceptInvitationResponse, error)
	RevokeInvitation(context.Context, *RevokeInvitationRequest) (*RevokeInvitationResponse, error)
	ListPendingInvitations(context.Context, *ListPendingInvitationsRequest) (*ListPendingInvitationsResponse, error)
	RemoveMember(context.Context, *RemoveMemberRequest) (*RemoveMemberResponse, error)
	UpdateMemberRole(context.Context, *UpdateMemberRoleRequest) (*UpdateMemberRoleResponse, error)
	ListMembers(context.Context, *ListMembersRequest) (*ListMembersResponse, error)
	TransferOwnership(context.Context, *TransferOwnershipRequest) (*TransferOwnershipResponse, error)
	// Team Encryption Keys
	GetTeamPublicKey(context.Context, *GetTeamPublicKeyRequest) (*GetTeamPublicKeyResponse, error)
	// User Encryption Keys (for personal sessions)
	GetUserPublicKey(context.Context, *GetUserPublicKeyRequest) (*GetUserPublicKeyResponse, error)
	// Get approved team skills for syncing to plugin as SKILL.md files
	GetTeamSkills(context.Context, *GetTeamSkillsRequest) (*GetTeamSkillsResponse, error)
	// Create a team skill draft from the plugin (local → team push)
	CreateTeamSkill(context.Context, *CreateTeamSkillRequest) (*CreateTeamSkillResponse, error)
	mustEmbedUnimplementedSessionHubServiceServer()
}

// UnimplementedSessionHubServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSessionHubServiceServer struct{}

func (UnimplementedSessionHubServiceServer) ValidateApiKey(context.Context, *ValidateApiKeyRequest) (*ValidateApiKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateApiKey not implemented")
}
func (UnimplementedSessionHubServiceServer) GetProjects(context.Context, *GetProjectsRequest) (*GetProjectsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProjects not implemented")
}
func (UnimplementedSessionHubServiceServer) CreateProject(context.Context, *CreateProjectRequest) (*Project, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProject not implemented")
}
func (UnimplementedSessionHubServiceServer) CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedSessionHubServiceServer) UpsertSession(context.Context, *CreateSessionRequest) (*UpsertSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertSession not implemented")
}
func (UnimplementedSessionHubServiceServer) GetSession(context.Context, *GetSessionRequest) (*Session, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedSessionHubServiceServer) UpdateSession(context.Context, *UpdateSessionRequest) (*Session, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSession not implemented")
}
func (UnimplementedSessionHubServiceServer) StreamInteractions(grpc.ClientStreamingServer[StreamInteractionsRequest, StreamInteractionsResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamInteractions not implemented")
}
func (UnimplementedSessionHubServiceServer) AddInteractionsBatch(context.Context, *AddInteractionsBatchRequest) (*AddInteractionsBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddInteractionsBatch not implemented")
}
func (UnimplementedSessionHubServiceServer) GetProjectObservations(context.Context, *GetProjectObservationsRequest) (*GetProjectObservationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProjectObservations not implemented")
}
func (UnimplementedSessionHubServiceServer) GetUserPreferences(context.Context, *GetUserPreferencesRequest) (*GetUserPreferencesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserPreferences not implemented")
}
func (UnimplementedSessionHubServiceServer) UploadAttachment(context.Context, *UploadAttachmentRequest) (*UploadAttachmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadAttachment not implemented")
}
func (UnimplementedSessionHubServiceServer) UploadPlanFile(context.Context, *UploadPlanFileRequest) (*UploadPlanFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadPlanFile not implemented")
}
func (UnimplementedSessionHubServiceServer) GetSessionQuota(context.Context, *GetSessionQuotaRequest) (*GetSessionQuotaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSessionQuota not implemented")
}
func (UnimplementedSessionHubServiceServer) CreateTeam(context.Context, *CreateTeamRequest) (*Team, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTeam not implemented")
}
func (UnimplementedSessionHubServiceServer) GetTeam(context.Context, *GetTeamRequest) (*Team, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTeam not implemented")
}
func (UnimplementedSessionHubServiceServer) UpdateTeam(context.Context, *UpdateTeamRequest) (*Team, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTeam not implemented")
}
func (UnimplementedSessionHubServiceServer) DeleteTeam(context.Context, *DeleteTeamRequest) (*DeleteTeamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTeam not implemented")
}
func (UnimplementedSessionHubServiceServer) ListUserTeams(context.Context, *ListUserTeamsRequest) (*ListUserTeamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUserTeams not implemented")
}
func (UnimplementedSessionHubServiceServer) InviteMember(context.Context, *InviteMemberRequest) (*InviteMemberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InviteMember not implemented")
}
func (UnimplementedSessionHubServiceServer) AcceptInvitation(context.Context, *AcceptInvitationRequest) (*AcceptInvitationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcceptInvitation not implemented")
}
func (UnimplementedSessionHubServiceServer) RevokeInvitation(context.Context, *RevokeInvitationRequest) (*RevokeInvitationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeInvitation not implemented")
}
func (UnimplementedSessionHubServiceServer) ListPendingInvitations(context.Context, *ListPendingInvitationsRequest) (*ListPendingInvitationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPendingInvitations not implemented")
}
func (UnimplementedSessionHubServiceServer) RemoveMember(context.Context, *RemoveMemberRequest) (*RemoveMemberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveMember not implemented")
}
func (UnimplementedSessionHubServiceServer) UpdateMemberRole(context.Context, *UpdateMemberRoleRequest) (*UpdateMemberRoleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMemberRole not implemented")
}
func (UnimplementedSessionHubServiceServer) ListMembers(context.Context, *ListMembersRequest) (*ListMembersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMembers not implemented")
}
func (UnimplementedSessionHubServiceServer) TransferOwnership(context.Context, *TransferOwnershipRequest) (*TransferOwnershipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferOwnership not implemented")
}
func (UnimplementedSessionHubServiceServer) GetTeamPublicKey(context.Context, *GetTeamPublicKeyRequest) (*GetTeamPublicKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTeamPublicKey not implemented")
}
func (UnimplementedSessionHubServiceServer) GetUserPublicKey(context.Context, *GetUserPublicKeyRequest) (*GetUserPublicKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserPublicKey not implemented")
}
func (UnimplementedSessionHubServiceServer) GetTeamSkills(context.Context, *GetTeamSkillsRequest) (*GetTeamSkillsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTeamSkills not implemented")
}
func (UnimplementedSessionHubServiceServer) CreateTeamSkill(context.Context, *CreateTeamSkillRequest) (*CreateTeamSkillResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTeamSkill not implemented")
}
func (UnimplementedSessionHubServiceServer) mustEmbedUnimplementedSessionHubServiceServer() {}
func (UnimplementedSessionHubServiceServer) testEmbeddedByValue()                           {}

// UnsafeSessionHubServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SessionHubServiceServer will
// result in compilation errors.
type UnsafeSessionHubServiceServer interface {
	mustEmbedUnimplementedSessionHubServiceServer()
}

func RegisterSessionHubServiceServer(s grpc.ServiceRegistrar, srv SessionHubServiceServer) {
	// If the following call pancis, it indicates UnimplementedSessionHubServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SessionHubService_ServiceDesc, srv)
}

func _SessionHubService_ValidateApiKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateApiKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionHubServiceServer).ValidateApiKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionHubService_ValidateApiKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionHubServiceServer).ValidateApiKey(ctx, req.(*ValidateApiKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionHubService_GetProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionHubServiceServer).GetProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionHubService_GetProjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionHubServiceServer).GetProjects(ctx, req.(*GetProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionHubService_CreateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionHubServiceServer).CreateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionHubService_CreateProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionHubServiceServer).CreateProject(ctx, req.(*CreateProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionHubService_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionHubServiceServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionHubService_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionHubServiceServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionHubService_UpsertSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionHubServiceServer).UpsertSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionHubService_UpsertSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionHubServiceServer).UpsertSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionHubService_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionHubServiceServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionHubService_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionHubServiceServer).GetSession(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionHubService_UpdateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionHubServiceServer).UpdateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionHubService_UpdateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionHubServiceServer).UpdateSession(ctx, req.(*UpdateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionHubService_StreamInteractions_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SessionHubServiceServer).StreamInteractions(&grpc.GenericServerStream[StreamInteractionsRequest, StreamInteractionsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SessionHubService_StreamInteractionsServer = grpc.ClientStreamingServer[StreamInteractionsRequest, StreamInteractionsResponse]

func _SessionHubService_AddInteractionsBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddInteractionsBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionHubServiceServer).AddInteractionsBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionHubService_AddInteractionsBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionHubServiceServer).AddInteractionsBatch(ctx, req.(*AddInteractionsBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionHubService_GetProjectObservations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectObservationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionHubServiceServer).GetProjectObservations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionHubService_GetProjectObservations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionHubServiceServer).GetProjectObservations(ctx, req.(*GetProjectObservationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionHubService_GetUserPreferences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserPreferencesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionHubServiceServer).GetUserPreferences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionHubService_GetUserPreferences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionHubServiceServer).GetUserPreferences(ctx, req.(*GetUserPreferencesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionHubService_UploadAttachment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadAttachmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionHubServiceServer).UploadAttachment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionHubService_UploadAttachment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionHubServiceServer).UploadAttachment(ctx, req.(*UploadAttachmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionHubService_UploadPlanFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadPlanFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionHubServiceServer).UploadPlanFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionHubService_UploadPlanFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionHubServiceServer).UploadPlanFile(ctx, req.(*UploadPlanFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionHubService_GetSessionQuota_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionQuotaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionHubServiceServer).GetSessionQuota(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionHubService_GetSessionQuota_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionHubServiceServer).GetSessionQuota(ctx, req.(*GetSessionQuotaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionHubService_CreateTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionHubServiceServer).CreateTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionHubService_CreateTeam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionHubServiceServer).CreateTeam(ctx, req.(*CreateTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionHubService_GetTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionHubServiceServer).GetTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionHubService_GetTeam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionHubServiceServer).GetTeam(ctx, req.(*GetTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionHubService_UpdateTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionHubServiceServer).UpdateTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionHubService_UpdateTeam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionHubServiceServer).UpdateTeam(ctx, req.(*UpdateTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionHubService_DeleteTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionHubServiceServer).DeleteTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionHubService_DeleteTeam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionHubServiceServer).DeleteTeam(ctx, req.(*DeleteTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionHubService_ListUserTeams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserTeamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionHubServiceServer).ListUserTeams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionHubService_ListUserTeams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionHubServiceServer).ListUserTeams(ctx, req.(*ListUserTeamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionHubService_InviteMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InviteMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionHubServiceServer).InviteMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionHubService_InviteMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionHubServiceServer).InviteMember(ctx, req.(*InviteMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionHubService_AcceptInvitation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptInvitationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionHubServiceServer).AcceptInvitation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionHubService_AcceptInvitation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionHubServiceServer).AcceptInvitation(ctx, req.(*AcceptInvitationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionHubService_RevokeInvitation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeInvitationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionHubServiceServer).RevokeInvitation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionHubService_RevokeInvitation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionHubServiceServer).RevokeInvitation(ctx, req.(*RevokeInvitationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionHubService_ListPendingInvitations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPendingInvitationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionHubServiceServer).ListPendingInvitations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionHubService_ListPendingInvitations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionHubServiceServer).ListPendingInvitations(ctx, req.(*ListPendingInvitationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionHubService_RemoveMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionHubServiceServer).RemoveMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionHubService_RemoveMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionHubServiceServer).RemoveMember(ctx, req.(*RemoveMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionHubService_UpdateMemberRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMemberRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionHubServiceServer).UpdateMemberRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionHubService_UpdateMemberRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionHubServiceServer).UpdateMemberRole(ctx, req.(*UpdateMemberRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionHubService_ListMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionHubServiceServer).ListMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionHubService_ListMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionHubServiceServer).ListMembers(ctx, req.(*ListMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionHubService_TransferOwnership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferOwnershipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionHubServiceServer).TransferOwnership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionHubService_TransferOwnership_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionHubServiceServer).TransferOwnership(ctx, req.(*TransferOwnershipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionHubService_GetTeamPublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTeamPublicKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionHubServiceServer).GetTeamPublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionHubService_GetTeamPublicKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionHubServiceServer).GetTeamPublicKey(ctx, req.(*GetTeamPublicKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionHubService_GetUserPublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserPublicKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionHubServiceServer).GetUserPublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionHubService_GetUserPublicKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionHubServiceServer).GetUserPublicKey(ctx, req.(*GetUserPublicKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionHubService_GetTeamSkills_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTeamSkillsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionHubServiceServer).GetTeamSkills(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionHubService_GetTeamSkills_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionHubServiceServer).GetTeamSkills(ctx, req.(*GetTeamSkillsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionHubService_CreateTeamSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTeamSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionHubServiceServer).CreateTeamSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionHubService_CreateTeamSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionHubServiceServer).CreateTeamSkill(ctx, req.(*CreateTeamSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SessionHubService_ServiceDesc is the grpc.ServiceDesc for SessionHubService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SessionHubService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sessionhub.SessionHubService",
	HandlerType: (*SessionHubServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateApiKey",
			Handler:    _SessionHubService_ValidateApiKey_Handler,
		},
		{
			MethodName: "GetProjects",
			Handler:    _SessionHubService_GetProjects_Handler,
		},
		{
			MethodName: "CreateProject",
			Handler:    _SessionHubService_CreateProject_Handler,
		},
		{
			MethodName: "CreateSession",
			Handler:    _SessionHubService_CreateSession_Handler,
		},
		{
			MethodName: "UpsertSession",
			Handler:    _SessionHubService_UpsertSession_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _SessionHubService_GetSession_Handler,
		},
		{
			MethodName: "UpdateSession",
			Handler:    _SessionHubService_UpdateSession_Handler,
		},
		{
			MethodName: "AddInteractionsBatch",
			Handler:    _SessionHubService_AddInteractionsBatch_Handler,
		},
		{
			MethodName: "GetProjectObservations",
			Handler:    _SessionHubService_GetProjectObservations_Handler,
		},
		{
			MethodName: "GetUserPreferences",
			Handler:    _SessionHubService_GetUserPreferences_Handler,
		},
		{
			MethodName: "UploadAttachment",
			Handler:    _SessionHubService_UploadAttachment_Handler,
		},
		{
			MethodName: "UploadPlanFile",
			Handler:    _SessionHubService_UploadPlanFile_Handler,
		},
		{
			MethodName: "GetSessionQuota",
			Handler:    _SessionHubService_GetSessionQuota_Handler,
		},
		{
			MethodName: "CreateTeam",
			Handler:    _SessionHubService_CreateTeam_Handler,
		},
		{
			MethodName: "GetTeam",
			Handler:    _SessionHubService_GetTeam_Handler,
		},
		{
			MethodName: "UpdateTeam",
			Handler:    _SessionHubService_UpdateTeam_Handler,
		},
		{
			MethodName: "DeleteTeam",
			Handler:    _SessionHubService_DeleteTeam_Handler,
		},
		{
			MethodName: "ListUserTeams",
			Handler:    _SessionHubService_ListUserTeams_Handler,
		},
		{
			MethodName: "InviteMember",
			Handler:    _SessionHubService_InviteMember_Handler,
		},
		{
			MethodName: "AcceptInvitation",
			Handler:    _SessionHubService_AcceptInvitation_Handler,
		},
		{
			MethodName: "RevokeInvitation",
			Handler:    _SessionHubService_RevokeInvitation_Handler,
		},
		{
			MethodName: "ListPendingInvitations",
			Handler:    _SessionHubService_ListPendingInvitations_Handler,
		},
		{
			MethodName: "RemoveMember",
			Handler:    _SessionHubService_RemoveMember_Handler,
		},
		{
			MethodName: "UpdateMemberRole",
			Handler:    _SessionHubService_UpdateMemberRole_Handler,
		},
		{
			MethodName: "ListMembers",
			Handler:    _SessionHubService_ListMembers_Handler,
		},
		{
			MethodName: "TransferOwnership",
			Handler:    _SessionHubService_TransferOwnership_Handler,
		},
		{
			MethodName: "GetTeamPublicKey",
			Handler:    _SessionHubService_GetTeamPublicKey_Handler,
		},
		{
			MethodName: "GetUserPublicKey",
			Handler:    _SessionHubService_GetUserPublicKey_Handler,
		},
		{
			MethodName: "GetTeamSkills",
			Handler:    _SessionHubService_GetTeamSkills_Handler,
		},
		{
			MethodName: "CreateTeamSkill",
			Handler:    _SessionHubService_CreateTeamSkill_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamInteractions",
			Handler:       _SessionHubService_StreamInteractions_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/sessionhub.proto",
}
